#%RAML 1.0
---
title: Node-Mock-Proxy-API
version: v1
baseUri: http://localhost/api

types:
  MockBase:
    type: object
    properties:
      name: string
      description: string
      request:
        type: object
        properties:
          uri: string
          method: string
          body: string
      response:
        type: object
        properties:
          body: string
  MockFull:
    type: MockBase
    properties:
      id: string
      fileName: string
      enabled: boolean

/requests:
  get:
    description: List all requests
    queryParameters:
      limit:
        type: number
        description: The number of results to be shown
      offset:
        type: number
        description: The offset of the result set
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: object
              properties:
                id: string
                request:
                    type: object
                    properties:
                        uri: string
                        method: string
                        body: string
                response:
                    type: object
                    properties:
                        body: string
            example: |
              [
                {
                  "id": "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
                  "request": {
                    "uri": "/path/to/get-request?foo=bar",
                    "method": "GET",
                    "body": ""
                  },
                  "response": {
                    "body": {foo:bar}"
                  }
                },
                {
                  "id": "1234567-12c4-11e1-840d-7b25c5ee775a",
                  "request": {
                    "uri": "/path/to/post-request",
                    "method": "POST",
                    "body": {type:something}"
                  }
                  "response": {
                    "body": {foo:buzz}"
                  }
                }
              ]
  delete:
    description: delete all logged request
    responses:
      200:
        description: All good, all requests have been deleted
  /{id}:
    get:
      description: Get a single request
      responses:
        200:
          body:
            application/json:
              type: object
                properties:
                  id: string
                  request:
                      type: object
                      properties:
                          uri: string
                          method: string
                          body: string
                  response:
                      type: object
                      properties:
                          body: string
              example: |
                {
                  "id": "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
                  "request": {
                    "uri": "/path/to/get-request?foo=bar",
                    "method": "GET",
                    "body": ""
                  },
                  "response": {
                    "body": {foo:bar}"
                  }
                }
/mocks:
  get:
    description: List all mocks (enabled and disabled)
    queryParameters:
      limit:
        type: number
        description: The number of results to be shown
      offset:
        type: number
        description: The offset of the resultset
      enabled:
        type: boolean
        description: Filter enabled mocks
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: MockFull
            example: |
              [
                {
                  "id": "684fb90",
                  "fileName": "foo.json",
                  "name": "Mock name",
                  "description": "Some description",
                  "request": {
                    "uri": "/path/to/getMock",
                    "method": "GET",
                    "body": ""
                  },
                  "response": {
                    "body": "{foo:bar}"
                  },
                  "enabled": true
                },
                {
                  "id": "1234567",
                  "fileName": "bar.json",
                  "name": "Another Mock name",
                  "description": "Another description",
                  "request": {
                    "uri": "/path/to/postMock",
                    "method": "POST",
                    "body": "{foo:baz}"
                  },
                  "response": {
                    "body": "{foo:baz}"
                  },
                  "enabled": false
                }
              ]
    /getReturnedMocks
      get:
          description: List mocks which have been returned to the caller. The do not net to be active anymore.
          queryParameters:
            limit:
              type: number
              description: The number of results to be returned.
          responses:
            200:
              body:
                application/json:
                  type: array
                  items:
                    type: MockFull
                  example: |
                    [
                      {
                        "id": "684fb90",
                        "fileName": "foo.json",
                        "name": "Mock name",
                        "description": "Some description",
                        "request": {
                          "uri": "/path/to/getMock",
                          "method": "GET",
                          "body": ""
                        },
                        "response": {
                          "body": "{foo:bar}"
                        }
                      },
                      {
                        "id": "1234567",
                        "fileName": "bar.json",
                        "name": "Another Mock name",
                        "description": "Another description",
                        "request": {
                          "uri": "/path/to/postMock",
                          "method": "POST",
                          "body": "{foo:baz}"
                        },
                        "response": {
                          "body": "{foo:baz}"
                        }
                      }
                    ]
  post:
    description: Create a new mock (initially disabled, id is generated)
    body:
      application/json:
        type: MockBase
        example: |
          {
            "name": "Another Mock name",
            "description": "Another description",
            "request": {
              "uri": "/path/to/postMock",
              "method": "POST",
              "body": "{foo:baz}"
            },
            "response": {
              "body": "{foo:baz}"
            }
          }
  /{id}:
    get:
      description: Get a single mock
      responses:
        200:
          body:
            application/json:
              type: MockFull
              example: |
                {
                  "id": "1234567",
                  "fileName": "bar.json",
                  "name": "Another Mock name",
                  "description": "Another description",
                  "request": {
                    "uri": "/path/to/postMock",
                    "method": "POST",
                    "body": "{foo:baz}"
                  },
                  "response": {
                    "body": "{foo:baz}"
                  },
                  "enabled": false
                }
    delete:
      description: delete a certain mock
      responses:
        200:
          description: All good, mock has been deleted
    /enable:
      put:
        description: Enable a mock
        responses:
          200:
            description: Mock has been enabled
            body:
              application/json:
                type: MockFull
                example: |
                  {
                    "id": "1234567",
                    "fileName": "bar.json",
                    "name": "Another Mock name",
                    "description": "Another description",
                    "request": {
                      "uri": "/path/to/postMock",
                      "method": "POST",
                      "body": "{foo:baz}"
                    },
                    "response": {
                      "body": "{foo:baz}"
                    },
                    "enabled": false
                  }
      /disable:
        put:
          description: Disable a mock
          responses:
            200:
              description: Mock has been disabled
              body:
                application/json:
                  type: MockFull
                  example: |
                    {
                      "id": "1234567",
                      "fileName": "bar.json",
                      "name": "Another Mock name",
                      "description": "Another description",
                      "request": {
                        "uri": "/path/to/postMock",
                        "method": "POST",
                        "body": "{foo:baz}"
                      },
                      "response": {
                        "body": "{foo:baz}"
                      },
                      "enabled": false
                    }
